# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: elastos-smartweb-service.nucleusconsole.com

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Elastos Smartweb Service gRPC API
apis:
- name: common.Common
- name: hive.Hive
- name: wallet.Wallet
- name: sidechain_eth.SidechainEth

#
# API usage restrictions.
#
usage:
  rules:
  - selector: common.Common.GenerateAPIRequest
    allow_unregistered_calls: true
  - selector: common.Common.GetAPIKey
    allow_unregistered_calls: true
  - selector: hive.Hive.UploadAndSign
    allow_unregistered_calls: true
  - selector: hive.Hive.VerifyAndShow
    allow_unregistered_calls: true
  - selector: wallet.Wallet.CreateWallet
    allow_unregistered_calls: true
  - selector: wallet.Wallet.ViewWallet
    allow_unregistered_calls: true
  - selector: wallet.Wallet.RequestELA
    allow_unregistered_calls: true
  - selector: sidechain_eth.SidechainEth.DeployEthContract
    allow_unregistered_calls: true
  - selector: sidechain_eth.SidechainEth.WatchEthContract
    allow_unregistered_calls: true