# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SmartWebService

on:
  push:
    branches: [ git_actions ]
  pull_request:
    branches: [ git_actions ]

jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: git_actions
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python tools
      run: |
        uname -a
        sudo apt-get clean && sudo apt-get update
        sudo apt-get upgrade
        sudo apt autoremove
        sudo apt-get install python3
        sudo apt-get install python3-setuptools 
        sudo apt-get install python3-pip
        sudo apt-get install -y apt-utils
        sudo pip3 install virtualenv
          
    - name: Install Docker
      run: |
        sudo apt-get remove docker docker-engine docker.io
        sudo apt install docker.io
        sudo systemctl unmask docker
        sudo systemctl start docker
        sudo systemctl enable docker
        docker --version
        
    - name: Start Database
      run: |
        cd tools
        ./postgres_test.sh yes
        cd ..
        
    - name: Start Private Net
      run: |
        docker build -t cyberrepublic/elastos-smartweb-service .
        docker container stop elastos-smartweb-service || true && docker container rm -f elastos-smartweb-service || true
        docker run --name elastos-smartweb-service -v "$PWD/.env:/elastos-smartweb-service/.env" -p 8001:8001 cyberrepublic/elastos-smartweb-service:latest
        
    - name: Install virtualenv and Run Unit Test
      run: | 
        virtualenv -p `which python3` venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        export PYTHONPATH="$PYTHONPATH:$PWD/grpc_adenine/stubs/"
        cp .env.example .env
        cp .env.example .env.test
        sh test.sh
      
    #- name: Run Unit Test
      #run : 
        #sh test.sh
        
    - name: Docker cleanup
      run: |
        docker container stop elastos-smartweb-service || true && docker container rm -f elastos-smartweb-service || true
        docker container rm -f smartweb-postgres-test
        deactivate
